# Reference: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main", "new-metrics"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: AL3X-69
          template: classic
          base: header
          config_timezone: Europe/Paris
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, sass
          commits_authoring: 26258257+AL3X-69@users.noreply.github.com
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_user: .user.login
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
#          plugin_achievements: yes # AWAITING FIX
#          plugin_achievements_secrets: yes
#          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
